### ISSUE TITLE
ERROR:  Exception thrown while making HTTP request!

### ISSUE THREAD

**Issue by Yamini-TWG** [jenkinsci/osf-builder-suite-for-sfcc-deploy-plugin#3]
Hi, 
I have configured OSF plugin to development environment as below, it worked all good but when I changed the host-name to my staging environment(staging-<realm>.demandware.net) it started failing with the error below. Can someone please help me in understanding what I am doing wrong. 

Thank you

Plugin configuration in jenkins file -
osfBuilderSuiteForSFCCDeploy(
                    hostname: "<hostname>",
                    bmCredentialsId: "abcdefghijklmn",
                    ocCredentialsId: "abcdefghijklmnopqr",
                    ocVersion: 'v19_5',
                    buildVersion: "dev",
                    createBuildInfoCartridge: true,
                    sourcePaths: [
                            [sourcePath: "src/cartridges"]
                    ],
                    actuvateBuild: true,
                    tempDirectory: 'tmp/build'
            )

error-

ERROR: 
Exception thrown while making HTTP request!
org.apache.http.NoHttpResponseException: staging-<realm>.demandware.net:443 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.jenkinsci.plugins.osfbuildersuiteforsfcc.deploy.OpenCommerceAPI.createCodeVersion(OpenCommerceAPI.java:173)
	at org.jenkinsci.plugins.osfbuildersuiteforsfcc.deploy.DeployBuilder$DeployCallable.invoke(DeployBuilder.java:1371)
	at org.jenkinsci.plugins.osfbuildersuiteforsfcc.deploy.DeployBuilder$DeployCallable.invoke(DeployBuilder.java:534)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3042)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by danechitoaie** [comment]
Based on the error `org.apache.http.NoHttpResponseException` the SFCC server did not returned a valid HTTP response. I assume you used the correct hostname and not `staging-.demandware.net`.

Are you getting this error every time you run the build? Or was it one time only? Can you make a HTTPS request to same hostname using something else like curl or Postman?

**Comment by Yamini-TWG** [comment]
I am getting this error every time I give staging hostname  (staging-realm-customer.demandware.net) if I replace hostname with development (development-realm-customer.demandware.net) its working fine. 

Staging environment:
I ran curl command 

H:\>curl https://staging-xxxx-xxxxxxx.demandware.net
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
        <title>404 URL Not Found</title>
        <link rel="STYLESHEET" type="text/css" href="/waroot/style.css">
</head>
<body>
        <h1>URL Not Found</h1>
        <img src="/waroot/system_arrow.gif" width="21" height="21" alt="" border="0">
        <p class="system_info">
                The requested URL was not found on this server.
        </p>
        <hr>
</body>
</html>

curl  https://staging-xxx-xxxxx.demandware.net/on/demandware.servlet/webdav/Sites/Cartridge

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
        <title>401 - Authorization Required.</title>
        <link rel="STYLESHEET" type="text/css" href="/waroot/style.css">
</head>
<body>
        <h1>Authorization Required</h1>
        <img src="/waroot/system_arrow.gif" width="21" height="21" alt="" border="0">
        <p class="system_info">
                This request requires HTTP authentication.
        </p>
        <hr>
</body>
</html>

when I open this url in my browser 
https://staging-xxxx-xxxx.demandware.net/on/demandware.servlet/webdav/Sites/Cartridges
it's asking for authentication and showing me the the cartridges. 



********Note - I see same results from cli and browser when I use my development hostname

**Comment by danechitoaie** [comment]
Is there any way to send me a private message/email with the actual domain? So I can try and test on my end? I'm not sure how else I can help since I'm not able to reproduce the error on my end.

**Comment by danechitoaie** [comment]
Actually from what I see the error happens when it attempts to create the code version `createCodeVersion` and I see you attempt to do this on a staging instance where two factor auth is required to be able to upload code. So you need too setup the two factor auth credentials (client SSL cert/key) and use `cert.staging.realm.customer.demandware.net` as hostname instead of `staging-realm-customer.demandware.net`

**Comment by Yamini-TWG** [comment]
thank you, we couldnot even push cartridges from local machine, so we believe something is wrong from our end. Will fix it and update you. 
Thank you again
